#ifndef HELPER_WIDGETS_H
#define HELPER_WIDGETS_H

#define MARGIN_HALF 4
#define MARGIN_DEFAULT 8
#define MARGIN_DOUBLE 16
#define MARGIN_TRIPLE 24
#define CALENDAR_COLOR_SELECTION_DIALOG_HEIGHT 149
#define CALENDAR_COLOR_SELECTION_ICON_WIDTH 102

#endif
